---
# For more options, see https://docs.honeybadger.io/lib/ruby/gem-reference/configuration

<% deployment = Screenote::Deployment.current %>
api_key: <%= (deployment.monitoring_configuration[:api_key] || "").to_json %>

# The environment your app is running in.
env: "<%= Rails.env %>"

# The absolute path to your project folder.
root: "<%= Rails.root.to_s %>"

# Honeybadger won't report errors in these environments.
development_environments:
- test
- development
- cucumber

# Enable verbose debug logging (useful for troubleshooting).
debug: false

exceptions:
  enabled: <%= deployment.monitoring? %>
  local_variables: false

request:
  disable_session: <%= deployment.self_hosted? %>
  disable_params: <%= deployment.self_hosted? %>
  disable_environment: <%= deployment.self_hosted? %>
  disable_url: <%= deployment.self_hosted? %>

breadcrumbs:
  enabled: <%= deployment.saas? && deployment.monitoring? %>

# Enable Honeybadger Insights
insights:
  enabled: <%= deployment.saas? && deployment.monitoring? %>
